- lang/ko_KR.trn
Is this how I'm supposed to do it? If not, just copy paste these...
> Update Korean translation

- lang/cs_CZ.trn
- lang/de_DE.trn
- lang/fr_FR.trn
- lang/ko_KR.trn
- lang/nl_NL.trn
- lang/template.trn
Now I understand how to synch forks.
> Added more Translation Strings

- lang/de_DE.trn
- pymclevel/minecraft.yaml
What do you mean with a bullet? @LaChal 
A bullet from a pistol or what? :D
> Updated de_DE.trn

- lang/ko_KR.trn
Will you manually add again? ㅠㅠ
> Update Korean Translation (NBT got even harder!)

- js/scripts.js
> Website - Some minor fixes

- lang/cs_CZ.trn
- lang/de_DE.trn
- lang/fr_FR.trn
- lang/ko_KR.trn
- lang/nl_NL.trn
- lang/template.trn
I made the spaces that it matches with the template, sorry if this is wrong.
> Added more Strings and updated German Translation

- lang/ko_KR.trn
Not good:        Updated trnaslations with missremoved strings and added a new string.
At least better: Updated translations with misremoved strings and added a new string.
> Update Korean Translation and correct grammar pls!

- editortools/filter.py
Rewrote filter loading, but no side effects besides the <filter file name>.pyc files being placed in the directory where mcedit.py is in.
> Filter categories

- lang/de_DE.trn
As you might expect, it fills the empty translations. In german.
However i am not happy on the t782 and t783-translations. 
@MobileCrafter Have you a better translation or an idea? If not, then this could be merged.
> Updated German localisation

- pymclevel/minecraft.yaml
> Fixed Slime Block Opacity(Transparency)

- lang/de_DE.trn
Title says it.
Translated: 91, 366, 367, 501, 503, 741, 794, 797, 798, 799, 800, 801
There were also some extra lines, i corrected them: 97, 223, 231, 261, 282, 506, 722
However, could someone explain these?: (their context, functionality)
`o714 Ticks mode `**`accouplement`**
`o795 Width of blocks movement: `
`o796 Width of selection movement: `
> Updated german translation

- lang/ko_KR.trn
This is why I love releases on weekends. I can only spend my time on GitHub on weekends!
> Not Good Timing Korean Translation Update

- about.html
> Fix images not showing

- about.html
- contributors.html
- index.html
- requirements.html
- template.html
- Added `<!DOCTYPE html>`
- Added `lang="en-US"` to `<html>`
- Added `<meta charset="utf-8">`
- Added `<link rel="shortcut icon" href="favicon.ico">`
> Changes to website

- lang/zh-CN.trn
update new lines 836-839 in Chinese translation
> Update new lines. 

- lang/de_DE.trn
Update to a clean german which contains more friendly languange. I change a lot of translations which sounds like Google Translations. By the way German is my native language.
> Update German Translation

- lang/de_DE.trn
I change some translations to a better german and add some points after
ending of sentences.
> small update for German Translation

- lang/zh_TW.trn
* Create zh_TW language file which based on zh_CN language file.
* Add zh_TW fonts (otf file)
> Create zh_TW language file

- lang/de_DE.trn
First part was pull request #394.
> DE-Translation: Revised strings 1001 to 1821

- lang/ko_KR.trn
● To dev
- Some are [Recommended] and others are (Nor Recommended), possibly choose either [] or ()?
- Hover text (explanation?) should all have '.' or not have at all?
● To Korean Translator: World= 맵(현재), 월드?, 세계? <월드가 좋을 듯>
> Update Korean Translation (~852)

- pymclevel/pocket.yaml
fixed list: snow layer, invisible bedrock(needs texture), pillar quartz block, wooden (double) slabs, changed one of duplicated podzol to grass path(texture was correct), changed stonecutter texture, edited update game blocks, needs testing on id 253, 254, 255
> Fixed some errors

- lang/ko_KR.trn
What happened to some of the missing lines?
> Update Korean Translation(~857)

- pymclevel/blockrotation.py
- pymclevel/minecraft.yaml
- renderer.py
In this pull request I have fixed fence gates rotations and mirroring. Now they act like any other block with a direction.
I have also added a renderer for fence gates(they show if they are open and in which direction they are open):
> Fence gates changes 

- pymclevel/pocket.yaml
> wooden_slab id

- lang/de_DE.trn
I also referred to p.g. F# as F#/Gb ( = Fis/Ges in German)
> Translated new strings (German)

- README.md
with the "--recursive" command you get Mojang's latest LevelDB on default when cloning. :)
> just an addition

- pymclevel/pocket.yaml
If any of these need block model change in other files, please tell me.
- Nether Brick Fence
- Snow Layers
- Nether Portal Block
- Mob Head
> Updated to MCPE 0.12 build 5

- pymclevel/pocket.yaml
> Fixed half slab rendering issues

- lang/de_DE.trn
Translated strings 151, 462 and 910 to 933
> Updated translations

- lang/ko_KR.trn
Inform me if any missing string exists.
> Update Korean Translation (~942)

- lang/sv_SE.trn
Added Swedish language with so far around 500 translations :)
Some translations might be a bit incorrect since some English words we
don't have in Swedish.
**One questions though**: Is this the only file necessary to add the Swedish language? Or do I need to change some other file(s) too? (I haven't looked at anything more than the lang folder so far)
> Added Swedish language

- lang/de_DE.trn
> Updated German translations

- albow/file_dialogs.py
- directories.py
- resource_packs.py
The data directory is now found by the location of a python file instead of relying on the current working directory
> Merge DataDirectoryChanges branch into master

- lang/de_DE.trn
See #597 
`Du kannst vielleicht alle Funktionen erreichen.` sounds wierd and is unusual. In english, it would be something like `You may be able to reach all functions.`
I would use `Sie könnten vielleicht nicht alle Funktionen erreichen.`, which is more accurate to the english one and more usual. (`You may not be able to reach all functions.`)
> Fix german translation 950

- pymclevel/minecraft_server.py
> Raise radius to improve performance

- lang/de_DE.trn
Update the german translations for 951 to 954.
> Updated german translation (951 - 955)

- leveleditor.py
Also registered leveleditor to the logger.
> Fixed #974

- editortools/filter.py
- leveleditor.py
- pymclevel/schematic.py
- Added File Input options that filters can use
- Added option to remove error dialog when developing filters
- Added dynamic data module for filters
- Fixed Structure coordinate rounding (@Marcono1234) (#727)
- Removed StructureTooBigException, since Minecraft can import structures bigger than 32x32x32 (@Azounstone) (#722)
- Fixed bug with removing TileEntity coordinates while converting from Schematic to Structure (@Marcono1234) (#728)
> Merge Features for filters branch

- pymclevel/pocket.yaml
For pocket.yaml for missing PE blocks
> Added more missing PE Blocks

- editortools/filter.py
This is probably one of the most unnecessary commits since it just adds a missing character in a comment, but I just happened to notice it so xD
> Fix spelling error

- albow/file_dialogs.py
- editortools/filter.py
Thanks to @LaChal for pointing the issue out
> Fixed removed import in filter.py

- README.md
Update and simplify instructions for running from source.  Fixes #883.
> Docs: Improve instructions for running from source
